<?php
defined('MVC_APP') or die('Access denied');
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coding Souls Dashboard</title>
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="App/views/css/estil.css">
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2a59fbfff2.js" crossorigin="anonymous"></script>

</head>

<body>

    <!-- SECCIO DEL HEADER -->
    <div class="container-fluid header p-0">
        <header class="d-flex flex-wrap justify-content-center p-2 align-items-center w-100 bg-body">
            <div class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
                <a href="index.php">
                    <img alt="logo" class="logotip" height="50px" src="App/views/images/logo.png">
                </a>
                <div id="text">
                    <div id="effect" class="d-flex">
                        <span class="ms-1 fs-4">Coding Souls</span>
                    </div>
                </div>
            </div>
        </header>
    </div>

    <div class="container-fluid d-flex mt-5 mb-4 justify-content-around align-items-start">
        <div class="col-9 bg-white rounded p-4">
            <div class="row">
                <div class="col-9">
                    <h2 class="text-uppercase text-dark"><span class="fw-bold">Missatges rebuts</span></h2>
                </div>
                <div class="col">
                    <div class="row">
                        <div class="col d-flex justify-content-end">
                            <a href="index.php?action=view_save_message" class="btn btn-outline-success me-2">Nou missatge</a>
                            <a href="index.php?action=dashboard" class="btn btn-danger">Tornar</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row px-5 justify-content-center">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Assumpte</th>
                            <th scope="col">Enviat per</th>
                            <th scope="col">Data enviament</th>
                            <th scope="col">Accions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (!empty($info_messenger_received)) : ?>
                            <?php foreach ($info_messenger_received as $message) : ?>
                                <tr class=" <?= ($message['data_apertura'] == null ? 'fw-bold' : '') ?>">
                                    <td><?= $message['assumpte'] ?></td>
                                    <td><?= $message['emissor'] ?></td>
                                    <td><?= date('d/m/Y', strtotime($message['data_env'])) ?></td>
                                    <td class="text-center">
                                        <a href="index.php?action=view_message&id=<?= $message['id'] ?>" class="btn btn-success">Obrir</a>
                                        <a href="index.php?action=pdf_message&id=<?= $message['id'] ?>" class="btn btn-info">PDF</a>
                                        <a href="index.php?action=delete_message&id=<?= $message['id'] ?>" class="btn btn-danger">Eliminar</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <tr>
                                <td colspan="4" class="text-center">No hi ha missatges rebuts</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-2 bg-white rounded text-dark p-4">
            <div class="row">
                <div class="col">
                    <p><span class="fw-bold text-uppercase">Usuari</span>: <?= $_SESSION['username'] ?></p>
                </div>
            </div>
            <?php if ($level >= 5) : ?>
                <div class="row">
                    <div class="row border-bottom text-center">
                        <div class="col">
                            <p class="text-secondary fw-bold text-uppercase">Administració</p>
                        </div>
                    </div>
                    <ul class="nav d-flex flex-column ps-2">
                        <?php if ($level == 10) : ?>
                            <li class="nav-item">
                                <a href="index.php?action=manage_users" class="text-dark">Gestió usuaris</a>
                            </li>
                        <?php endif; ?>
                        <li class="nav-item">
                            <a href="index.php?action=manage_news" class="text-dark">Gestió notícies</a>
                        </li>
                    </ul>
                </div>
            <?php endif; ?>
            <div class="row border-bottom text-center mt-3">
                <div class="col">
                    <p class="text-secondary">Opcions d'usuari</p>
                </div>
            </div>
            <div class="row mt-2">
                <ul class="nav d-flex flex-column ps-2">
                    <li class="nav-item mb-3">
                        <a class="text-dark" href="index.php?action=change_pass">Canviar contrasenya</a>
                    </li>
                    <li class="nav-item">
                        <a href="index.php?action=logout" class="btn btn-danger w-100">Desconnectar</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid d-flex mt-5 mb-4 ms-0 justify-content-around align-items-start">
        <div class="col-9 bg-white rounded p-4">
            <div class="row">
                <div class="col-9">
                    <h2 class="text-uppercase text-dark"><span class="fw-bold">Missatges enviats</span></h2>
                </div>
            </div>
            <div class="row px-5 justify-content-center">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Assumpte</th>
                            <th scope="col">Receptor</th>
                            <th scope="col">Data enviament</th>
                            <th scope="col">Accions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (!empty($info_messenger_sent)) : ?>
                            <?php foreach ($info_messenger_sent as $message) : ?>
                                <tr>
                                    <td><?= $message['assumpte'] ?></td>
                                    <td><?= $message['receptor'] ?></td>
                                    <td><?= date('d/m/Y', strtotime($message['data_env'])) ?></td>
                                    <td class="text-center">
                                        <a href="index.php?action=view_save_message&id=<?= $message['id']?>" class="btn btn-info">Reenviar</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <tr>
                                <td colspan="4" class="text-center">No hi ha missatges enviats</td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

</html>