<?php
defined('MVC_APP') or die('Permission denied');
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message <?= $message['id'] ?></title>

    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="App/views/css/estil.css">
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2a59fbfff2.js" crossorigin="anonymous"></script>


</head>

<body>
    <div class="container-fluid header p-0">
        <header class="d-flex flex-wrap justify-content-center p-3 align-items-center w-100 bg-body">
            <div class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
                <a href="#">
                    <img alt="logo" class="logotip" height="50px" src="App/views/images/logo.png">
                </a>
                <div id="text">
                    <div id="effect" class="d-flex">
                        <span class="ms-1 fs-4">Coding Souls</span>
                    </div>
                </div>
            </div>

            <ul class="nav nav-pills text-decoration-none">
                <li class="nav-item"><a href="index.php" class="nav-link active">Home</a></li>
                <li class="nav-item"><a href="index.php?action=login" class="nav-link">Accedeix</a></li>
                <li class="nav-item"><a href="index.php?action=register" class="nav-link">Registrar-se</a></li>
                <li class="nav-item"><a href="https://reskyt.com/ca/educacio/iescaparrella/formulari/t-3764" class="nav-link">Contacta'ns</a></li>
            </ul>
        </header>
    </div>

    <!-- SECCIO DE LA NOTICIA -->
    <div class="container mt-auto rounded-3">
        <div class="row justify-content-around">
            <div class="col-12 news p-3 bg-secondary text-white">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h1><?= $message['assumpte'] ?></h1>
                    </div>
                    <div class="col text-end">
                        <ul class="list-inline p-0">
                            <li class="list-inline-item"><?= $message['emissor'] ?>,</li>
                            <li class="list-inline-item text-dark"><?= date('d/m/Y', strtotime($message['data_env'])) ?></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row text-justify">
            <div class="col-12 news p-5 bg-body text-dark">
                <div class="row">
                    <div class="col-12">
                        <p><?= $message['text'] ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-auto bg-dark h-10 justify-content-end">
            <div class="col-12 text-end">
                <a href="index.php?action=view_messenger" class="btn btn-info my-3">Torna</a>
                <a href="index.php?action=delete_message&id=<?= $message['id'] ?>" class="btn btn-danger my-3">Eliminar</a>
            </div>
        </div>


    </div>



    <!-- SECCIO DEL FOOTER -->
    <div class="container-fluid mt-auto footer bottom">
        <div class="row p-5 bg-body text-dark">
            <div class="col-xs-12 col-md-6 col-lg-3 d-flex flex-column">
                <img src="App/views/images/logo-capa.png" style="width:300px;" alt="logo_capa">
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3 d-flex flex-column">
                <p class="h5">Xarxes socials</p>
                <ul class="footer-nav nav d-flex flex-column">
                    <li class='nav-item '>
                        <a class="nav-link" href="https://www.facebook.com/inscaparrella/">
                            <i class="fa fa-facebook-square menus-fa-2x" aria-hidden="true" style="color: rgb(121, 121, 121);"></i>
                            Facebook
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="https://twitter.com/inscaparrella?lang=en">
                            <i class="fa fa-twitter-square menus-fa-2x" aria-hidden="true" style="color: rgb(121, 121, 121);"></i>
                            Twitter
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="https://www.youtube.com/user/InstitutCaparrella/videos">
                            <i class="fa fa-youtube-play menus-fa-2x" aria-hidden="true" style="color: rgb(121, 121, 121);"></i>
                            Youtube
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="https://www.instagram.com/inscaparrella/">
                            <i class="fa fa-instagram menus-fa-2x" aria-hidden="true" style="color: rgb(121, 121, 121);"></i>
                            Instagram
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-xs-12 col-md-6 col-lg-3 d-flex flex-column">
                <p class="h5">Centre</p>
                <ul class="footer-nav nav d-flex flex-column">
                    <li class='nav-item '>
                        <a class="nav-link">
                            Comunicació Centre - Família
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            Calendari i llibres de text curs 2022-2023
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            Racó dels pares
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            AMPA
                        </a>
                    </li>
                </ul>

            </div>
            <div class="col-xs-12 col-md-6 col-lg-3">
                <p class="h5">Contacte</p>
                <ul class="footer-nav nav d-flex flex-column">
                    <li class='nav-item widget-title'>
                        <a class="nav-link" href="#">
                            IES Caparrella
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            Partida Caparrella 98
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            25192 Lleida
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="tel:973288180">
                            Tel: 973 28 81 80
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link">
                            Fax: 973280195
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="mailto:iescaparrella@iescaparrella.cat">
                            iescaparrella@iescaparrella.cat
                        </a>
                    </li>
                    <li class='nav-item '>
                        <a class="nav-link" href="https://reskyt.com/ca/educacio/iescaparrella/formulari/t-3764">
                            Contacta&#039;ns
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script>
        let toast = document.querySelector('.toast');
        if (toast) {
            let toastAlert = new bootstrap.Toast(toast);
            toastAlert.show();
        }
    </script>

</body>

</html>