<?php
defined('MVC_APP') or die('Access denied');
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="App/views/css/formularis.css">
    <script defer src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2a59fbfff2.js" crossorigin="anonymous"></script>
</head>

<body class="register">
    <div class="register-container d-flex align-items-center justify-content-center vh-100">
        <div class="container w-75">
            <div class="row box-shadow">
                <div class="col bg-register d-none d-lg-block col-md-5 col-lg-5 col-xl-6 rounded-start" loading="lazy"></div>
                <div class="col bg-body px-5 pb-5 rounded-end">
                    <!-- Logo -->
                    <div class="d-flex text-end close-container mb-5">
                        <a id="close-btn" href="index.php"><i class="fa-regular fa-circle-xmark fa-xl text-dark"></i></a>
                    </div>

                    <div class="d-flex align-items-center">
                        <a href="index.php" class="text-decoration-none d-flex text-dark align-items-center">
                            <img class="me-2" src="App/views/images/logo.png" loading="lazy" alt="" width="48" />
                            <div id="text">
                                <div id="effect" class="d-flex">
                                    <span class="fs-4">Coding Souls</span>
                                </div>
                            </div>
                        </a>
                    </div>
                    <h2 class="fw-bold text-center py-5">Uneix-te a nosaltres rei</h2>

                    <!-- Formulari login -->
                    <form action="index.php?action=register_user" method="POST">
                        <div class="row mb-3">
                            <div class="col-6">
                                <label for="username" class="text-uppercase mb-1">Nom d'usuari</label>
                                <input type="text" name="nick" class="form-control" id="username" placeholder="Nom d'usuari" required />
                            </div>
                            <div class="col">
                                <label for="names" class="text-uppercase mb-1">Nom i cognoms</label>
                                <input type="text" name="nomcognoms" class="form-control" id="names" placeholder="Nom,cognoms" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-8">
                                <label for="email" class="text-uppercase mb-1">Correu electrònic</label>
                                <input type="email" name="mail" class="form-control" id="email" placeholder="Email" required />
                                <div class="form-helper">
                                    <small class="text-muted">Tranquil, no t'enviarem spam</small>
                                </div>
                            </div>
                            <div class="col">
                                <label for="age" class="text-uppercase mb-1">Edat</label>
                                <input type="number" name="edat" class="form-control" id="age" placeholder="Edat" required />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                <label for="password" class="text-uppercase form-label mb-1">Contrasenya</label>
                                <input type="password" name="contrasenya" class="form-control" id="password" placeholder="Contrasenya" required />
                                <div class="form-helper">
                                    <small class="text-muted">La contrasenya ha de tenir almenys 8 caràcters</small>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Registra't</button>
                    </form>

                    <!-- Iniciar sessio amb RRSS -->
                    <div class="container w-100 my-4">
                        <div class="row text-center">
                            <div class="col-12">Registra't amb les xarxes socials</div>
                        </div>
                        <div class="row my-3">
                            <div class="col-12 col-xl mb-2">
                                <button class="btn btn-outline-primary w-100">
                                    <div class="row align-items-center">
                                        <div class="col-md-2 d-none d-md-block">
                                            <img src="App/views/images/twitter.png" alt="" width="36" />
                                        </div>
                                        <div class="col-12 col-md-10 text-center">Twitter</div>
                                    </div>
                                </button>
                            </div>
                            <div class="col-12 col-xl mb-2">
                                <button class="btn btn-outline-danger w-100">
                                    <div class="row align-items-center">
                                        <div class="col-md-2 d-none d-md-block">
                                            <img src="App/views/images/google.png" alt="" width="36" />
                                        </div>
                                        <div class="col-12 col-md-10 text-center">Google</div>
                                    </div>
                                </button>
                            </div>
                            <div class="col-12 col-xl mb-2">
                                <button class="btn btn-outline-dark w-100">
                                    <div class="row align-items-center">
                                        <div class="col-md-2 d-none d-md-block">
                                            <img src="App/views/images/twitch.png" alt="" width="auto" height="36" />
                                        </div>
                                        <div class="col-12 col-md-10 text-center">Twitch</div>
                                    </div>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="mt-3">
                        <span>Ja tens un compte? <a href="index.php?action=login">Connecta't</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>