<?php
session_start();
defined('MVC_APP') or die('Access denied');

echo "<pre>";
print_r ($_SESSION);
echo "</pre>";

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coding Souls Dashboard</title>
    <link rel="stylesheet" href="../../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../App/views/css/estil.css">
    <script src="../../assets/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2a59fbfff2.js" crossorigin="anonymous"></script>

</head>

<body>

    <!-- SECCIO DEL HEADER -->
    <div class="container-fluid header p-0">
        <header class="d-flex flex-wrap justify-content-center p-2 align-items-center w-100 bg-body">
            <div class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
                <a href="#">
                    <img alt="logo" class="logotip" height="50px" src="../../App/views/images/logo.png">
                </a>
                <div id="text">
                    <div id="effect" class="d-flex">
                        <span class="ms-1 fs-4">Coding Souls</span>
                    </div>
                </div>
            </div>

            <ul class="nav nav-pills text-decoration-none">
                <li class="nav-item"><a href="index.php" class="nav-link active">Home</a></li>
                <li class="nav-item"><a href="index.php?action=login" class="nav-link">Log In</a></li>
                <li class="nav-item"><a href="index.php?action=register" class="nav-link">Register</a></li>
                <li class="nav-item"><a href="webo" class="nav-link">FAQs</a></li>
                <li class="nav-item"><a href="webo" class="nav-link">About</a></li>
            </ul>
        </header>
    </div>

    <div class="container-fluid d-flex mt-5 mb-4 justify-content-around">
        <div class="col-9 bg-white rounded p-4">
            <h2 class="text-uppercase text-dark"><span class="fw-bold">Benvinguts</span> al portal genèric</h2>
        </div>
        <div class="col-2 bg-white rounded text-dark p-4">
            <div class="row">
                <div class="col">
                    <p><span class="fw-bold text-uppercase">Usuari</span>: <?= $_SESSION['username'] ?></p>
                </div>
            </div>

            <div class="row">
                <div class="row border-bottom text-center">
                    <div class="col">
                        <p class="text-secondary fw-bold text-uppercase">Administració</p>
                    </div>
                </div>
                <ul class="nav d-flex flex-column ps-2">
                    <li class="nav-item">
                        <a href="index.php?action=manage_users" class="text-dark">Gestió usuaris</a>
                    </li>
                    <li class="nav-item">
                        <a href="index.php?action=manage_news" class="text-dark">Gestió notícies</a>
                    </li>
                </ul>
            </div>
            <div class="row border-bottom text-center mt-3">
                <div class="col">
                    <p class="text-secondary">Opcions d'usuari</p>
                </div>
            </div>
            <div class="row mt-2">
                <ul class="nav d-flex flex-column ps-2">
                    <li class="nav-item mb-3">
                        <a class="text-dark" href="index.php?action=change_pass">Canviar contrasenya</a>
                    </li>
                    <li class="nav-item">
                        <a href="index.php?action=logout" class="btn btn-danger w-100">Desconnectar</a>
                    </li>
                </ul>
            </div>
        </div>


</body>

</html>